Implement Features
myuk96/exadel-bonus-plus pull request #16
Opened 2021-02-15 14:47 UTC by ElbekDeveloper

The following features are implemented in this pull request: 
1. Search Vendor by name feature 
2. Simplification of vendor model as requested by frontend guys 
3. Initial test for vendor service

2021-02-15 20:37 UTC, myuk96 requested changes

2021-02-15 20:37 UTC, myuk96 commented on ExadelBonusPlus.DataAccess/VendorRepository.cs
> +            return await GetCollection().AsQueryable().Where(v=> v.Name.ToLower().Contains(name.ToLower())).ToListAsync(cancellationToken);
in which query is it going to serialize?

2021-02-15 20:37 UTC, myuk96 commented on ExadelBonusPlus.Services.Models/MapperProfile.cs
> +            //From dto to model
the comment is useless

2021-02-15 20:37 UTC, myuk96 commented on ExadelBonusPlus.WebApi/IServiceCollectionExtensions.cs
> +            services.AddScoped<IValidator<AddVendorDto>, AddVendorDtoValidator>();
is it going to be different for every request?
why scoped?

2021-02-16 08:04 UTC, ElbekDeveloper commented on ExadelBonusPlus.DataAccess/VendorRepository.cs
> +            return await GetCollection().AsQueryable().Where(v=> v.Name.ToLower().Contains(name.ToLower())).ToListAsync(cancellationToken);
That is temporary implementation of search. It uses linq. This week during the refactoring, I will come back to this part and will be realizing the search via indexes in mongodb

2021-02-16 08:07 UTC, ElbekDeveloper commented on ExadelBonusPlus.Services.Models/MapperProfile.cs
> +            //From dto to model
Updated

2021-02-16 08:24 UTC, merged