All add controllers v2
myuk96/exadel-bonus-plus pull request #28
Opened 2021-02-24 19:21 UTC by EXAN7742

2021-02-24 20:57 UTC, myuk96 requested changes

2021-02-24 20:57 UTC, myuk96 commented on ExadelBonusPlus.WebApi/Controllers/V2/BonusesController.cs
> +        public async Task<ActionResult<ResultDto<BonusDto>>> AddBonusAsync([FromBody] AddBonusDto Bonus)
URL should be like that
vendors/{id : guid}/bonuses

2021-02-24 20:57 UTC, myuk96 commented on ExadelBonusPlus.WebApi/Controllers/V2/BonusesController.cs
> +        public async Task<ActionResult<ResultDto<IEnumerable<BonusDto>>>> FindBonusByIdAsync([FromRoute] Guid id)
is there a case when we gather more than 1 item by id?
I don't think it should be list here
and change name to Get
the diffenets between Get and FInd is Find can return empty empty if there is no items despite GET returns NotFound() status

2021-02-24 20:57 UTC, myuk96 commented on ExadelBonusPlus.WebApi/Controllers/V2/BonusesController.cs
> +        [Route("{id}/activate")]
try to avoid verbs in routes when follow REST
let's make it as bonuses/{id: guid}/status/{value: bool}

2021-02-24 20:57 UTC, myuk96 commented on ExadelBonusPlus.WebApi/Controllers/V2/BonusesController.cs
> +    [Route("api/v{version:apiVersion}/[controller]")]
make it start from lower-case
bonuses instead of Bonuses

2021-02-24 20:57 UTC, myuk96 commented on ExadelBonusPlus.WebApi/Controllers/V2/HistoryController.cs
> +    [Route("api/v{version:apiVersion}/[controller]")]
histories

2021-02-24 20:57 UTC, myuk96 commented on ExadelBonusPlus.WebApi/Controllers/V2/HistoryController.cs
> +    public class HistoryController : ControllerBase
Change name to UserActivitiesController

2021-02-24 20:57 UTC, myuk96 commented on ExadelBonusPlus.WebApi/Controllers/V2/HistoryController.cs
> +        public async Task<ActionResult<HistoryDto>> AddHistory([FromBody] AddHistoryDTO history)
post users/{guid: id}/bonuses/{guid: id}/bonus-usages
payload: {
"dateTime": value,
"raiting" 0,
}

2021-02-24 20:57 UTC, myuk96 commented on ExadelBonusPlus.WebApi/Controllers/V2/HistoryController.cs
> +        public async Task<ActionResult<HistoryDto>> GetAllHistory()
it looks vulnerable for web-crawlers 
so, usually we add paging opportunity and rate limit , but for now it's ok

2021-02-24 20:57 UTC, myuk96 commented on ExadelBonusPlus.WebApi/Controllers/V2/HistoryController.cs
> +        [Route(("users/{userId:Guid}"))]
users/{id:Guid}/bonus-usages?start=value&end=value

2021-02-24 20:57 UTC, myuk96 commented on ExadelBonusPlus.WebApi/Controllers/V2/HistoryController.cs
> +        [Route(("{historyId:Guid}/estimate"))]
/bonus-usages/{id: guid}/estimation
to estimate - verb
estimation - noun

2021-02-24 20:57 UTC, myuk96 commented on ExadelBonusPlus.WebApi/Controllers/V2/VendorsController.cs
> +    [Route("api/v{version:apiVersion}/[controller]")]
vendors

2021-02-24 20:57 UTC, myuk96 commented on ExadelBonusPlus.WebApi/Controllers/V2/VendorsController.cs
> +        [SwaggerResponse((int)HttpStatusCode.OK, Description = "Vendors Retrieved ", Type = typeof(ResultDto<IEnumerable<VendorDto>>))]
is name unique? if so, return one model
on other hand use query and return list, like: vendors?name=value

2021-02-24 21:31 UTC, EXAN7742 commented on ExadelBonusPlus.WebApi/Controllers/V2/BonusesController.cs
> +    [Route("api/v{version:apiVersion}/[controller]")]
It turned out to be solved by adding one line:
services.AddRouting(options => options.LowercaseUrls = true);

2021-02-25 08:41 UTC, myuk96 requested changes

2021-02-25 17:28 UTC, myuk96 approved these changes

2021-02-25 21:54 UTC, merged