Add repository
myuk96/exadel-bonus-plus pull request #3
Opened 2021-01-21 13:16 UTC by EXAN7742

+ add IRepository
+ add BaseRepository
* edit appsettings

2021-01-21 13:59 UTC, myuk96 commented on ExadelBonusPlus.DataAccess/BaseRepository.cs
> +        private readonly IConfiguration _configuration;
Try to use Options pattern instead
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0

2021-01-21 20:21 UTC, EXAN7742 commented on ExadelBonusPlus.DataAccess/BaseRepository.cs
> +using System.Linq.Expressions;
test comment

2021-01-22 11:35 UTC, myuk96 requested changes

2021-01-23 19:53 UTC, myuk96 requested changes

2021-01-24 11:19 UTC, myuk96 requested changes

2021-01-24 11:22 UTC, myuk96 requested changes

2021-01-24 11:22 UTC, myuk96 commented on ExadelBonusPlus.DataAccess/BaseRepository.cs
> +        public virtual async Task<TModel> Add(TModel obj)
Remove all "async" statement  without "await" statement

2021-01-24 11:38 UTC, myuk96 requested changes

2021-01-24 11:38 UTC, myuk96 commented on ExadelBonusPlus.DataAccess/BaseRepository.cs
> +        public virtual async Task<IEnumerable<TModel>> GetAll()
Make all method that returns Task with Async postfix to show consumers it explicitly

2021-01-25 14:15 UTC, myuk96 requested changes

2021-01-25 14:15 UTC, myuk96 commented on ExadelBonusPlus.DataAccess/BaseRepository.cs
> +            return Task.FromResult(GetCollection().Find(Builders<TModel>.Filter.Empty).ToList() as IEnumerable<TModel>);
just return ToListAsync()

2021-01-25 14:15 UTC, myuk96 commented on ExadelBonusPlus.DataAccess/BaseRepository.cs
> +            return Task.FromResult(obj);
it's not proper
in this case we are not waiting ReplaceOne operation and make it Fire and Forget one , that's bad in this particular case, so let's do not returns models on repository levels than we update it or remove it

2021-01-25 22:44 UTC, myuk96 requested changes

2021-01-25 22:44 UTC, myuk96 commented on ExadelBonusPlus.DataAccess/BaseRepository.cs
> +            return GetCollection().ReplaceOneAsync(Builders<TModel>.Filter.Eq("_id", id), obj, new UpdateOptions { IsUpsert = true }, cancellationToken);
Is it necessary to add new document if document with the Id does not exist?

2021-01-26 09:57 UTC, merged